### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by notmedia** [olvidalo/obsidian-chord-sheets#7]
Hi, thank you for this awesome plugin! It really helps to organise my chords, you made my day :)

I want to share my feedback, these things could be potential improvements.

1. Fonts in reading and edit views are different. Perhaps this plugin use own font for reading view, would be better if it used font from settings without any differences or have an option to set font for reading view.

Reading view:
<img width="657" alt="image" src="https://github.com/user-attachments/assets/726d7ccc-9fb7-4a46-83c6-b549c9cafc1e">

Edit view:
<img width="669" alt="image" src="https://github.com/user-attachments/assets/1f882510-f9c6-460b-aa00-87d938b5ecc8">

2. Add ability to write extra text on the same line with chords. Right now sometimes extra text breaks pasring chords in lyrics

<img width="679" alt="image" src="https://github.com/user-attachments/assets/d8106826-ecc3-4ad5-99ae-66941088ad35">

3. Sometimes autoscroll button disappears from the right top corner. Try to open any documents without chords and then go back

<img width="1078" alt="image" src="https://github.com/user-attachments/assets/5624d308-dec4-4223-b9fa-bb103b8e70e9">

4. Would be grate if I can revert transpose to the original (first saved or marked as original) if possible.

**Comment by olvidalo** [comment]
Thanks for your feedback!

> Fonts in reading and edit views are different. Perhaps this plugin use own font for reading view, would be better if it used font from settings without any differences or have an option to set font for reading view.

This has been improved in the latest release, see #6. 

> Add ability to write extra text on the same line with chords. Right now sometimes extra text breaks pasring chords in lyrics

The chord line detection "algorithm" in this plugin is really dumb: if more than half of the words look like chords, the line is deemed a chord line and only then chords in the line are parsed are highlighted. This prevents words such as "a" and "am" in text lines being highlighted as chords. I am hesitant to implement more sophisticated heuristics to detect mixed text / chord lines because for most cases it works really well as is and it will never be possible to catch all the edge cases.

However I might "borrow" the approach of marking lines explicitly as chord or lyrics lines from the [Chord Lyrics](https://github.com/nevernotmove/obsidian-chordlyrics?tab=readme-ov-file#mark-lines) plugin, where chord lines can be marked with `%c` and text lines with `%t` at the end of the line, overriding automatic detection. So for your mixed line you could write:
```
Am           G           F        E  (this text breaks highlighting) %c
Lorem ipsum
```

Forced text lines will mistakenly render some words as chords though, such as in
```
Am          G           F        E  (i am a forced text line) %c
Lorem ipsum
``` 

Where "am" and "a" would be highlighted. But this would still be better than no chord detection at all for mixed lines. What do you think, would something like this be helpful?

> Sometimes autoscroll button disappears from the right top corner. Try to open any documents without chords and then go back

Will look into this.

> Would be grate if I can revert transpose to the original (first saved or marked as original) if possible.

While I see the convenience of such a feature I think this is out this plugin's scope I'm afraid. Transposing is just an editing operation, so it can just be undone like other edits. Marking a version as the original would be better handled by dedicated versioning plugins such as the `git` plugin.

**Comment by notmedia** [comment]
Hi, thank you for response! 

> What do you think, would something like this be helpful?

This would be nice, but need to be an optional thing so I could set `%c` only on wrong parsed lines with chords without editing the whole lyrics.

> Transposing is just an editing operation, so it can just be undone like other edits.

Understood, you are right

**Comment by olvidalo** [comment]
The autoscroll button issue has been fixed in the latest release.

**Comment by gautamneeraj** [comment]
This is a great contribution to the Obsidian community! Thank you!!!

Is there an implementation to render Chords from this format?

```Chords
The [C]sun comes [G]up
It's a [D]new day [Em]dawning
```

**Comment by olvidalo** [comment]
Line markers and inline chords are supported in the latest release.

**Comment by gautamneeraj** [comment]
> Line markers and inline chords are supported in the latest release.

Thank you for including [C] as the line markers (e.g. [c] instead of %c)

Two Issues:
1. When transposing +1, [C] gets transposed but is not rendered [C#] bust as C#
2. Could you render the line marked Chords a line above the lyrics, right above where it should be
- Example:
The [C]sun comes [G]up
It's a [D]new day [Em]dawning

The Chords are displayed above the lyrics.

Thank you for all your hard work!!!! this is amazing.

**Comment by gautamneeraj** [comment]
> 1. When transposing +1, [C] gets transposed as C# without the []. The transposed chord should be inside []

Wow!!! you fixed it so quickly. Thank you!

**Comment by olvidalo** [comment]
Thanks for reporting the transpose issue. Appreciate your feedback!

> The Chords should be displayed right above the letters where they are placed.

I see why this feature could be useful, but for now I want to stick with the behaviour that is expected from code blocks, meaning: everything should be displayed exactly as is, nothing should be hidden or moved somewhere else. So I won't implement such a feature for now, sorry!

I'm going to lock this issue to keep this organized and to not spam the original author with more comment notifications :)
Please feel free to open one or more new single-topic issues if there's anything more.
